version: '3.9'

services:
  postgres-database:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres-database:/var/lib/postgresql/data'

volumes:
  postgres-database: